# Generated by Django 3.0.2 on 2020-01-13 06:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=1000)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, max_length=1000, null=True, upload_to='')),
                ('views_num', models.PositiveIntegerField(default=0)),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=1000)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, max_length=1000, null=True, upload_to='')),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('question_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='QnA.Question')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
